# Generated by Django 4.0.6 on 2022-07-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protesteaqui', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='cpf',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AddField(
            model_name='professor',
            name='disciplina',
            field=models.CharField(default='', max_length=124),
        ),
        migrations.AlterField(
            model_name='professor',
            name='idade',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='professor',
            name='nome',
            field=models.CharField(default='', max_length=124),
        ),
    ]
