# Generated by Django 4.0.5 on 2022-07-27 14:46

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protesteaqui', '0002_alter_avaliacao_professor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='atualizado_em',
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='criado_em',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='professor',
            name='idade',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
