# Generated by Django 4.0.6 on 2022-07-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protesteaqui', '0002_professor_cpf_professor_disciplina_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='cpf',
            field=models.CharField(default='', max_length=14),
        ),
    ]
