# Generated by Django 4.0.5 on 2022-07-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protesteaqui', '0003_remove_avaliacao_atualizado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
